### ISSUE TITLE
PAL support

### ISSUE THREAD

**Issue by hackgrid** [Polprzewodnikowy/N64FlashcartMenu#59]
### Description

I use a 64drive 1.0
The menu does flicker and is uneasy on the eyes on a PAL N64 console.
Would be great if PAL support could be added, so it is more pleasant for PAL users :-)

Thank you very much for your hard work and supporting the 64drive!

**Comment by riggles1** [comment]
Flickering doesn't make sense, 50Hz noticeably flickers, not 60Hz. Explain your setup (TV etc) and I can help you figure out what's wrong. The menu does not flicker on a PAL N64. There was no technical reason to suffer through 50Hz on the N64 back in 1996 and even less in 2023.

Please make it optional in that case, PAL N64 systems can do 60Hz (59.6Hz) without modifications, 59.9Hz with a DFO mod. 

99% of CRT's sold since the early 80s in Europe had 60Hz support due to strict EU requirements, RGB and 50-60Hz sync range. There's no need for 50Hz especially today! Even if your TV can't decode NTSC colors (some TVs can't do it in color) you can circumvent the black and white composite picture issue by RGB modding the N64 since RGB is free of color-encoding and is neither PAL or NTSC.

The default should be 60Hz, and a hidden config should let you switch it to 50Hz.

Us European N64 owners want our N64flashcartmenues to be in 60Hz. (Really hope nothing gets changed, a lot of people don't realize our TVs do 60Hz as well)

**Comment by Polprzewodnikowy** [comment]
If you can post a video that would be great. I don't really know what you describe as flickering. Menu is running in interlaced mode and due to how this mode works image might "flicker" in certain situations. But this doesn't line up - original 64drive menu also runs at 480i mode so it should also flicker.
Menu creates configuration file at `menu/config.ini`. Try changing `pal60=0` option to `pal60=1` to run menu in 60 Hz mode instead of default 50 Hz mode. And please report if this changes anything.

**Comment by TharathielCB** [comment]
I made two videos with this flickering. Captured with an OSSC and a HDMI grabber

Pal60=1
https://github.com/Polprzewodnikowy/N64FlashcartMenu/assets/99963785/93062319-e8c0-4493-b597-ece61bafa378

Pal60=0
https://github.com/Polprzewodnikowy/N64FlashcartMenu/assets/99963785/cbf9a922-2285-4faa-83f7-d11354afa344

It looks like a problem with an interlaced Signal.

**Comment by hackgrid** [comment]
@TharathielCB thanks for looking into that! :-)

**Comment by TharathielCB** [comment]
It seems to be the deinterlacer. If I deactivate BOB deinterlacing on the OSSC the image stabilize. 

https://github.com/Polprzewodnikowy/N64FlashcartMenu/assets/99963785/023197b6-da92-4962-9907-b4fd96988055

**Comment by TharathielCB** [comment]
Possible Solution: Change the Menu to progressive instead of interlaced. 
On ED64+ the Menu is progressive aswell.

**Comment by TheViper4Life** [comment]
> Possible Solution: Change the Menu to progressive instead of interlaced. On ED64+ the Menu is progressive aswell.

Hi, I know this post is a bit old...but I just got a SummerCart and I am too experiencing that jitter the user above mentioned. I'm running my US N64 via S-Video through RetroTink 2X Pro on an old 720p Vizio Flatpanel TV. 

Is this something that can be set in the Flashcart menu? I can't find that setting. This jitter seems to cause image retention on the TV as well, so I'd like to get rid of it if I can.

Thanks.

**Comment by networkfusion** [comment]
This issue was not closed on the 2025-03-31 release as it was a work around.

**Comment by networkfusion** [comment]
Libdragon has improved the video interface  (merged to preview menu)  this needs to be re-evaluated.

**Comment by networkfusion** [comment]
This issue was not closed on the 2025-11-15 release as it was a work around.

**Comment by networkfusion** [comment]
Libdragon has improved the video interface (merged to preview menu) this needs to be re-evaluated.

**Comment by networkfusion** [comment]
Should be fixed now, please check against the latest V0.3.2 release (enabling PAL60).

**Comment by hackgrid** [comment]
Thanks for your hard work and continued support guys! :-)

I tested with a fresh SDCARD install, and with the new PAL60 its better than without, but still not perfect.
For example I boot up the new libdragon-based Pandemonium ROM file, and the menu text there stays perfectly still without any jitter.

Or is that an 480i and 240p thing?

**Comment by networkfusion** [comment]
Closing as implemented (at least as far as this project is concerned).
